### ISSUE TITLE
Push COVID19 files into CKAN portal

### ISSUE THREAD

**Issue by reubano** [openpeoria/covid-19-il-data-scraper#1]
- [ ] create new `save_ckan_report` function ([s3 version](https://github.com/openpeoria/covid-19-il-data-scraper/blob/1951999240f6b0cb7cf76614ac766fafe506e256/app/api.py#L168))
- [ ] [ckanapi example](https://github.com/ckan/ckanapi#file-uploads)
- [ ] [ckanutils example](https://github.com/reubano/ckanny/blob/24c6fae5897704c32d2134d074cc19a22b645ae9/ckanny/datastorer.py#L78-L149)

**Comment by sottom** [comment]
- ckanutils is the usage of the ckan api wrapper in the ckanny cli
- ckanapi is the python api

**Comment by sottom** [comment]
I did not end up using the CKAN python api referenced above. I instead used the `reqeusts` python library to call the CKAN API directly. [The docs can be found here](https://docs.ckan.org/en/2.8/api/).
