### ISSUE TITLE
Update s3 upload script to make objects public by default

### ISSUE THREAD

**Issue by reubano** [openpeoria/covid-19-il-data-scraper#10]
@reubano The [bucket](https://covid19-il.s3.us-east-2.amazonaws.com/) is public, but the objects are not. I can't access the data to proceed. I keep getting 403 errors.

Could you give me the login info for the account that has this S3 bucket, or [give my account access](https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html) to the s3 bucket that holds the data in the aws console?

_Originally posted by @sottom in https://github.com/openpeoria/covid-19-il-data-scraper/issues/8#issuecomment-645666881_

**Comment by sottom** [comment]
Test this

**Comment by sottom** [comment]
This is dependent on the policy of the bucket it is being uploaded to (see [here](https://github.com/openpeoria/AWS-CKAN/issues/14)).
