### ISSUE TITLE
Back-fill data from s3 and push into ckan.

### ISSUE THREAD

**Issue by sottom** [openpeoria/covid-19-il-data-scraper#8]
Add a new function to back-fill CKAN with the historical data from s3.

**Comment by sottom** [comment]
@reubano The [bucket](https://covid19-il.s3.us-east-2.amazonaws.com/) is public, but the objects are not. I can't access the data to proceed. I keep getting 403 errors.

Could you give me the login info for the account that has this S3 bucket, or [give my account access](https://docs.aws.amazon.com/IAM/latest/UserGuide/tutorial_cross-account-with-roles.html) to the s3 bucket that holds the data in the aws console?

**Comment by reubano** [comment]
I just made all the objects public... https://s3.console.aws.amazon.com/s3/buckets/covid19-il/?region=us-east-2

**Comment by sottom** [comment]
The functionality to back-fill data from AWS is present in PR #2. You will simply need to run a call similar to this
```bash
http://localhost:5001/v1/report?dest=ckan&source=s3&days=200
```
