### ISSUE TITLE
Check overwrite option to see if it's working

### ISSUE THREAD

**Issue by sottom** [openpeoria/covid-19-il-data-scraper#9]
Make sure the option added to s3 isn't overwriting old data.

**Comment by sottom** [comment]
@reubano should I be checking the s3 version of the overwrite option too? Or just the `save_ckan_report` version?

**Comment by sottom** [comment]
So check the output to make sure it's detailed instead of checking the code. Is that right?

**Comment by reubano** [comment]
> So check the output to make sure it's detailed instead of checking the code. Is that right?

For s3, correct. For ckan its a matter of double checking the code and then verifying by checking the output.

**Comment by sottom** [comment]
Sounds good. I think PR #2 is ready for review and merge then.

**Comment by sottom** [comment]
This issue was closed because the overwrite option is preventing data from being overwritten unless you specify the overwrite option; however, specifying the overwrite option is not overwriting data as I expected, so I created #12.
